#all:
#  hosts:
#    192.168.182.130:

all:
  hosts:
    192.168.182.130:
      ansible_user: centos2  # Remplacez par le nom d'utilisateur
      ansible_ssh_private_key_file: ~/.ssh/authorized_keyz  # Chemin vers votre clé SSH
